server:
  port: 8080 # 개발 시에는 충돌 방지를 위해 일반적으로 8080을 사용

spring:
  datasource:
    # H2 인메모리 모드 설정
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # 웹 브라우저에서 H2 콘솔 접근 허용
      path: /h2-console # 접속 주소: localhost:8080/h2-console
      settings:
        web-allow-others: true

  # [로컬 DB 가이드]
  # 아래 설명을 따라가면 로컬 실행에서의 DB 상태를 눈으로 확인할 수 있습니다.
  # 1. 서버 실행 후 브라우저 접속: http://localhost:8080/h2-console
  # 2. 로그인 화면 설정 값
  #    - Driver Class: org.h2.Driver
  #    - JDBC URL: jdbc:h2:mem:testdb
  #    - User Name: sa
  #    - Password:
  # 3. Connect 버튼 클릭

  jpa:
    hibernate:
      ddl-auto: create-drop # 시작할 때 테이블 생성, 끄면 삭제
    properties:
      hibernate:
        format_sql: true # 로그에 SQL 예쁘게 출력
        show_sql: true # 실행되는 SQL을 콘솔에 출력
    defer-datasource-initialization: true # data.sql 초기화 데이터를 위해 필요

sentry:
  dsn: https://ddb0be7908d048d5a138b078f75daab9@glitchtip.supabin.com/3
  traces-sample-rate: 1.0
  environment: dev
  enable-tracing: true
  logging:
    enabled: true
    minimum-event-level: error
    minimum-breadcrumb-level: info

logging:
  level:
    root: INFO
    io.sentry: DEBUG # Sentry 디버그 로그 추가
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
