server:
  port: 80

#spring:
#  datasource:
#    # 1. 타임존 Asia/Seoul로 설정, 한글 깨짐 방지(characterEncoding)
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # 프로젝트 초기에는 update가 편리 (나중엔 validate 권장)
#    properties:
#      hibernate:
#        format_sql: true
#        # show_sql: true # 2. SQL 쿼리가 로그에 보이게 하려면 주석 해제
#    defer-datasource-initialization: true # data.sql 사용 시 필요
#
#logging:
#  level:
#    # 3. 배포 환경에서는 너무 많은 로그는 성능 저하 원인이 됨 - 필요할 때만 DEBUG로 바꾸기
#    root: INFO
#    # org.hibernate.SQL: DEBUG
#    # org.hibernate.type: TRACE